# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fleet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66leet.proto\x12\x05\x66leet\"S\n\rTelemetryData\x12\x0e\n\x06van_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x02\"\x18\n\x05\x41lert\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0c\x46leetMonitor\x12\x39\n\x0fStreamTelemetry\x12\x14.fleet.TelemetryData\x1a\x0c.fleet.Alert(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=22
  _globals['_TELEMETRYDATA']._serialized_end=105
  _globals['_ALERT']._serialized_start=107
  _globals['_ALERT']._serialized_end=131
  _globals['_FLEETMONITOR']._serialized_start=133
  _globals['_FLEETMONITOR']._serialized_end=206
# @@protoc_insertion_point(module_scope)
